TITLE="D.O.A. ★ Grind-Free Crafting Mod (extended)"
DESCRIPTION=$(cat << EOF
Tired of aimlessly searching materials to create craftable items, weapons, etc.  Look no further.

Add items to your inventory in the craft manager using this module.

[h1] Supported items [/h1]
[list]
  [*]Game defaults (Orca Island/Canyonlands)
  [*]Clothing, weapons, equipment, and more...
[/list]

[h1] Dependencies [/h1]
[list]
  [*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=3032452168]GrindFreeCrafting (defaults)[/url]
[/list]

[h1] Installation [/h1]
Add this module to your game server [b]hosting.cfg[/b]. Note the UGC order below.
[code] steam_ugc=3032452168,3032829638 [/code]

[h1] Reporting issues [/h1]
If you are experiencing an issue, or found a bug, you can [url=https://github.com/nuxy/MiscreatedMods-DOA/issues]report it here[/url].
EOF
)
CHANGENOTE="[url=https://github.com/nuxy/MiscreatedMods-DOA]Github project[/url]"
FILEID="3032829638"
