local item = FindInTable(ItemSpawnerManager.itemCategories, "category", "CraftingVendorInventory")
item.group =
{
	{ class = "RK_AA12", percent = 100 },
	{ class = "RK_ACAW", percent = 100 },
	{ class = "RK_AK74U", percent = 100 },
	{ class = "RK_AKM", percent = 100 },
	{ class = "RK_AP85", percent = 100 },
	{ class = "RK_AT15", percent = 100 },
	{ class = "RK_AUMP45", percent = 100 },
	{ class = "RK_Bulldog", percent = 100 },
	{ class = "RK_ColtPython", percent = 100 },
	{ class = "RK_Crossbow", percent = 100 },
	{ class = "RK_CX4Storm", percent = 100 },
	{ class = "RK_FlareGun", percent = 100 },
	{ class = "RK_G18Pistol", percent = 100 },
	{ class = "RK_hk45", percent = 100 },
	{ class = "RK_KrissV", percent = 100 },
	{ class = "RK_M16", percent = 100 },
	{ class = "RK_m1911a1", percent = 100 },
	{ class = "RK_M249", percent = 100 },
	{ class = "RK_M40A5", percent = 100 },
	{ class = "RK_M9A1", percent = 100 },
	{ class = "RK_Makarov", percent = 100 },
	{ class = "RK_MeleePrimary", percent = 100 },
	{ class = "RK_MeleeSecondary", percent = 100 },
	{ class = "RK_Mk18", percent = 100 },
	{ class = "RK_Model70", percent = 100 },
	{ class = "RK_MP5", percent = 100 },
	{ class = "RK_P350", percent = 100 },
	{ class = "RK_PX4", percent = 100 },
	{ class = "RK_R90", percent = 100 },
	{ class = "RK_RecurveBow", percent = 100 },
	{ class = "RK_Rem700", percent = 100 },
	{ class = "RK_Rem870", percent = 100 },
	{ class = "RK_ruger22", percent = 100 },
	{ class = "RK_Sako_85", percent = 100 },
	{ class = "RK_Shotgun870Tactical", percent = 100 },
	{ class = "RK_TranquilizerGun", percent = 100 },
	{ class = "RK_Wasteland22", percent = 100 },
	{ class = "RK_ClothingHelmetBallistic", percent = 100 },
	{ class = "RandomNormalRepairKit", percent = 100 },
	{ category = "RandomTraderCraftingGuides", percent = 100 },
}
