local item = FindInTable(ItemSpawnerManager.itemCategories, "category", "FoodVendorInventory")
item.group =
{
	{ class = "SeedsBeets", percent = 100 },
	{ class = "SeedsBrushPeas", percent = 100 },
	{ class = "SeedsCarrots", percent = 100 },
	{ class = "SeedsPotatoes", percent = 100 },
	{ class = "SeedsWatermelons", percent = 100 },
	{ class = "SeedsPumpkins", percent = 100 },
	{ class = "SeedsRadishes", percent = 100 },
	{ class = "SeedsSnapPeas", percent = 100 },
	{ class = "SeedsTomatoes", percent = 100 },
	{ class = "guide_cooking_1", percent = 100 },
	{ class = "guide_cooking_2", percent = 100 },
	{ class = "guide_cooking_3", percent = 100 },
	{ class = "ChickenCooked", percent = 40 },
	{ class = "HamCooked", percent = 40 },
	{ class = "BearMeatCooked", percent = 40 },
	{ class = "DeerMeatSteakCooked", percent = 40 },
	{ class = "WolfMeatSteakCooked", percent = 40 },
	{ class = "ClamSingle", percent = 40 },
	{ class = "AppleFresh", percent = 100 },
	{ class = "Berries", percent = 100 },
	{ class = "Honeycomb", percent = 80 },
	{ class = "PeanutButter", percent = 100 },
	{ class = "Jelly", percent = 100 },
	{ class = "CoffeeBag", percent = 100 },
	{ class = "Bread", percent = 100 },
	{ class = "CerealBox", percent = 100 },
	{ class = "BeerCan", percent = 50 },
	{ class = "Champagne", percent = 30 },
	{ class = "MiniBottleGin", percent = 25 },
	{ class = "MiniBottleVodka", percent = 25 },
	{ class = "MiniBottleWhiskey", percent = 45 },
	{ class = "ChocolateBox", percent = 40 },
	{ class = "EggNog", percent = 25 },
	{ class = "GingerBreadMan", percent = 25 },
	{ class = "HersheysBar", percent = 90 },
	{ class = "MRE", percent = 40 },
}
