TITLE="D.O.A. ★ "WTF" Builder Sandbox Map"
DESCRIPTION=$(cat << EOF
Endless sea of nothingness. Development sandbox used for MOD testing.

[h1] Installation [/h1]
[olist]
  [*]Add this module to your game server [b]hosting.cfg[/b]
    [code] steam_ugc=3033874012 [/code]
  [*]Run the map by updating your launch arguments
    [code] Bin64_dedicated/MiscreatedServer.exe ... +http_startserver +map sandbox [/code]
[/olist]

[h1] Reporting issues [/h1]
If you are experiencing an issue, or found a bug, you can [url=https://github.com/nuxy/MiscreatedMods-DOA/issues]report it here[/url].
EOF
)
CHANGENOTE="[url=https://github.com/nuxy/MiscreatedMods-DOA]Github project[/url]"
FILEID="3033874012"
