TITLE="D.O.A. ★ Alien Invasion Mod"
DESCRIPTION=$(cat << EOF
[quote] “It was a battleground of fear and curiosity.” - H.G. Wells, The War of the Worlds [/quote]

[h1] Mod Info [/h1]
[list]
  [*]Human Spider mutants only (e.g. [i]Aliens[/i]).
  [*]Aliens shoot radiating, explosive venom - far distances.
  [*]Aliens will aggressively melee when in close proximity.
  [*]Higher frequency of Random Air Drops, Plane and UFO crashes.
  [*]Increased enemy/horde spawning probability.
[/list]

[h1] Installation [/h1]
Add this module to your game server [b]hosting.cfg[/b]
[code] steam_ugc=2787393227 [/code]
EOF
)
CHANGENOTE="[url=https://github.com/nuxy/MiscreatedMods-DOA]Github project[/url]"
FILEID="2787393227"
