TITLE="D.O.A. ★ Air Drop Disabler"
DESCRIPTION=$(cat << EOF
Permanently disables the following in-game events:
[list]
  [*]AirDropChristmas
  [*]AirDropCrate
  [*]AirDropPlane
  [*]AirDropSantaCrate
  [*]AirPlaneCrash
  [*]UFOCrash
[/list]

[h1] Installation [/h1]
Add this module to your game server [b]hosting.cfg[/b]
[code] steam_ugc=3037782422 [/code]

[h1] Reporting issues [/h1]
If you are experiencing an issue, or found a bug, you can [url=https://github.com/nuxy/MiscreatedMods-DOA/issues]report it here[/url].
EOF
)
CHANGENOTE="[url=https://github.com/nuxy/MiscreatedMods-DOA]Github project[/url]"
FILEID="3037782422"
