TITLE="D.O.A. ★ Vote2Ban"
DESCRIPTION=$(cat << EOF
Using the [i]Chat console[/i] initiate a vote to ban cheaters, game hackers, or unwanted players.

[h1] Commands [/h1]
[code]
!vb player <name>
!vb players
[/code]

[h1] Dependencies [/h1]
[list]
  [*][url=https://steamcommunity.com/sharedfiles/filedetails/?id=1841357578]MisDB[/url]
[/list]

[h1] Installation [/h1]
[olist]
  [*]Add this module to your game server [b]hosting.cfg[/b]. Note the UGC order below.
[/olist]
[code] steam_ugc=1841357578[/code]
EOF
)
CHANGENOTE="[url=https://github.com/nuxy/MiscreatedMods-DOA]Github project[/url]"
FILEID=""
