TITLE="D.O.A. ★ Spawn Anywhere"
DESCRIPTION=$(cat << EOF
Create custom Spawn Points that override in-game defaults.

[h1] Mod Info [/h1]
[list]
  [*]Can be managed using the [i]Chat console[/i].
  [*]Supports unlimited instances.
[/list]

[h1] Commands [/h1]
[code]
!sp save <name>
!sp delete <RECORDID>
!sp list
[/code]

[h1] Installation [/h1]
Add this module to your game server [b]hosting.cfg[/b]
[code] steam_ugc=2787415227 [/code]
EOF
)
CHANGENOTE="[url=https://github.com/nuxy/MiscreatedMods-DOA]Github project[/url]"
FILEID="2787415227"
