TITLE="D.O.A. ★  Glasses Repair Kit Mod"
DESCRIPTION=$(cat << EOF
[h1] Mod Info [/h1]
[list]
  [*]Used to repair glasses like Aviators, Sunglasses, etc.
  [*]Can be used to repair itself.
  [*]The item cannot be sold.
[/list]

[h1] Installation [/h1]
Add this module to your game server [b]hosting.cfg[/b]
[code] steam_ugc=2787407832 [/code]
EOF
)
CHANGENOTE="[url=https://github.com/nuxy/MiscreatedMods-DOA]Github project[/url]"
FILEID="2787407832"
