TITLE="D.O.A. ★ Craftable Metal Storage Mod"
DESCRIPTION=$(cat << EOF
Tired of losing your hard-earned loot. Secure your most precious items in a safe.

[h1] Mod Info [/h1]
[list]
  [*]Used for storing gathered items securely (40 total).
  [*]Can only be accessed by you or your clan.
  [*]When health drops < 50% anyone can access.
  [*]Health is only reduced using a SledgeHammer or C4.
  [*]Supports 2 instances per base.
[/list]

[h1] Installation [/h1]
Add this module to your game server [b]hosting.cfg[/b]
[code] steam_ugc=2787400078 [/code]
EOF
)
CHANGENOTE="[url=https://github.com/nuxy/MiscreatedMods-DOA]Github project[/url]"
FILEID="2787400078"
