TITLE="D.O.A. ★ Plot Sign XL (Extra Large base)"
DESCRIPTION=$(cat << EOF
[h1] Mod Info [/h1]
[list]
  [*]Supports up to 600 base building items.
  [*]Base build radius has been increased.
[/list]

[h1] Installation [/h1]
Add this module to your game server [b]hosting.cfg[/b]
[code] steam_ugc=3034134938 [/code]

[h1] Reporting issues [/h1]
If you are experiencing an issue, or found a bug, you can [url=https://github.com/nuxy/MiscreatedMods-DOA/issues]report it here[/url].
EOF
)
CHANGENOTE="[url=https://github.com/nuxy/MiscreatedMods-DOA]Github project[/url]"
FILEID="3034134938"
