TITLE="D.O.A. ★ Free Taxi Teleport Mod"
DESCRIPTION=$(cat << EOF
This removes the [url=https://store.steampowered.com/news/app/299740/view/2463980472079899483]Safe Zone[/url] taxi “Fast Travel to Base“ amCoins requirement.

[h1] Installation [/h1]
Add this module to your game server [b]hosting.cfg[/b]
[code] steam_ugc=2789568378 [/code]
EOF
)
CHANGENOTE="[url=https://github.com/nuxy/MiscreatedMods-DOA]Github project[/url]"
FILEID="2789568378"
